spring:
  webflux:
    base-path: /v1

pokemon:
  api:
    url:
      base-path: 'https://pokeapi.co/api/v2'
      pokemon-path: '/pokemon?offset=%s&limit=%s'
    offset: 0
    limit: 99999
    buffer-size: 16777216 #in bytes
    cache-ttl: 3600 #in seconds
